[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
colosseum_prediction = "DCovAdAbKXxT21X7L6RTyCKZxpzAvDJh4rrBTagUF8RY"

[programs.mainnet]
colosseum_prediction = "8q3gx2TZ26ne8sETacwW8p7JLMeF4p4K7yEx9VGMRUiH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
